### ISSUE TITLE
Search for provider without a search term, gives entire default catalog

### ISSUE THREAD

**Issue by vbabuEM** [beckn/vendure#52] opened 2024-03-01 12:40 UTC

**Comment by vbabuEM** [comment] 2024-03-04 06:38
@sreekanthmr, I tried reproducing this error. However I do not get the complained behavior. Here is what I did.
1. I did search by provider with the following intent
`"intent": {
                "provider": {
                    "id": "nonexisting"
                }
            }`

I even tried the same with also an item search added to the provider search. However when such a search is requested, Vendure used to throw an exception No Channel with the token "nonexisting" could be found. There were no Beckn responses to BAP when this occurred. 

I wrote a new issue https://github.com/beckn/vendure/issues/53 to fix this to send back the error message all the way back to the BAP. 

However this original problem that we send back default catalog when we search for non-existant provider is not something I could reproduce. 

Can you please help me reproduce this through the request message or in our next call. Thanks.

**Comment by sreekanthmr** [comment] 2024-03-05 14:15
I think, provider.id mislead us.  When we use provider name in the search, it works as intended but we use code, it misbehaves.  We fixed this in BAP.  Now we are searching by provider name and it works well.

**Comment by vbabuEM** [comment] 2024-03-05 17:07
"message": {
            "intent": {
                "provider": {
                    "id": "nandi-coffee"
                }
            }
        }
        
        This should work. Here nandi-coffee is an id that was given in previous search listing under provider->id. 
        @sreekanthmr

**Comment by sreekanthmr** [comment] 2024-03-25 03:58
I'm not able to see the close issue button.  Please enable that so that, I can close the issues, which are resolved or not relevant.

**Closed** 2024-04-12 16:22 UTC
Labels: vendure

**Comment by sreekanthmr** [comment] 2024-04-12 19:39
I'm facing a different problem(s).  Here is the search term and this channel exists in the Vendure.
"intent": { "provider": { "id": "agrichem" } }
"agrichem" is channel code.  This produces "No channel with the token" response.  I change the search term to the following
"intent": { "provider": { "id": "agrichem-token" } }
This time I replace the channel id with channel token.
Results are showing but the response is repeating twice for every bpp.  Following is the response that I'm getting.  This may not be related to Vendure or the plugin but just wanted to share my observation.

{
    "context": {
        "ttl": "PT10M",
        "action": "search",
        "timestamp": "2024-04-12T19:34:40.514Z",
        "message_id": "e82a5ab1-3f8d-4789-85c9-e2d34e53305a",
        "transaction_id": "cc504a61-8389-4771-a9ff-d5e943c16f20",
        "domain": "retail:1.1.0",
        "version": "1.1.0",
        "bap_id": "kuza-agrinet-bap.com",
        "bap_uri": "https://bap-network.kuza.one",
        "location": {
            "country": {
                "code": "IND"
            },
            "city": {
                "code": "std:080"
            }
        }
    },
    "responses": [
        {
            "context": {
                "domain": "retail:1.1.0",
                "action": "on_search",
                "version": "1.1.0",
                "bpp_id": "kuza-agrinet-bpp.com",
                "bpp_uri": "https://bpp-network.kuza.one",
                "country": "IND",
                "city": "std:080",
                "location": {
                    "country": {
                        "code": "IND"
                    },
                    "city": {
                        "code": "std:080"
                    }
                },
                "bap_id": "kuza-agrinet-bap.com",
                "bap_uri": "https://bap-network.kuza.one",
                "transaction_id": "cc504a61-8389-4771-a9ff-d5e943c16f20",
                "message_id": "e82a5ab1-3f8d-4789-85c9-e2d34e53305a",
                "ttl": "PT10M",
                "timestamp": "2024-04-12T19:34:49.994Z"
            },
            "message": {
                "catalog": {
                    "descriptor": {
                        "name": "Vendure Shop Catalog"
                    },
                    "providers": [
                        {
                            "id": "agrichem-token",
                            "descriptor": {
                                "name": "Agrichem"
                            },
                            "categories": [
                                {
                                    "id": "687",
                                    "descriptor": {
                                        "code": "pesticides",
                                        "name": "pesticides"
                                    }
                                },
                                {
                                    "id": "691",
                                    "descriptor": {
                                        "code": "fertilizers",
                                        "name": "fertilizers"
                                    }
                                },
                                {
                                    "id": "694",
                                    "descriptor": {
                                        "code": "herbicide",
                                        "name": "herbicide"
                                    }
                                }
                            ],
                            "items": [
                                {
                                    "price": {
                                        "listed_value": "600.00",
                                        "currency": "KES",
                                        "value": "600.00"
                                    },
                                    "id": "3182",
                                    "category_ids": [
                                        "687"
                                    ],
                                    "descriptor": {
                                        "name": "Absolute 100",
                                        "long_desc": "<p>Absolute</p>",
                                        "images": [
                                            {
                                                "url": "http://bpp-app.kuza.one/assets/preview/44/unnamed__02__preview.png"
                                            }
                                        ]
                                    },
                                    "matched": true,
                                    "quantity": {
                                        "unitized": {
                                            "measure": {
                                                "value": "100",
                                                "unit": "ml"
                                            }
                                        }
                                    }
                                },
                                {
                                    "price": {
                                        "listed_value": "1600.00",
                                        "currency": "KES",
                                        "value": "1600.00"
                                    },
                                    "id": "3183",
                                    "category_ids": [
                                        "687"
                                    ],
                                    "descriptor": {
                                        "name": "Cuprocaffaro 2",
                                        "long_desc": "<p>Cuprocaffaro</p>",
                                        "images": [
                                            {
                                                "url": "http://bpp-app.kuza.one/assets/preview/92/cuprocaffaro__05__preview__preview.jpg"
                                            }
                                        ]
                                    },
                                    "matched": true,
                                    "quantity": {
                                        "unitized": {
                                            "measure": {
                                                "value": "2",
                                                "unit": "kg"
                                            }
                                        }
                                    }
                                },
                                {
                                    "price": {
                                        "listed_value": "100.00",
                                        "currency": "KES",
                                        "value": "100.00"
                                    },
                                    "id": "3184",
                                    "category_ids": [
                                        "687"
                                    ],
                                    "descriptor": {
                                        "name": "Duduthine",
                                        "long_desc": "<p>Duduthine</p>",
                                        "images": [
                                            {
                                                "url": "http://bpp-app.kuza.one/assets/preview/7b/duduthine__preview.png"
                                            }
                                        ]
                                    },
                                    "matched": true
                                },
                                {
                                    "price": {
                                        "listed_value": "5200.00",
                                        "currency": "KES",
                                        "value": "5200.00"
                                    },
                                    "id": "3185",
                                    "category_ids": [
                                        "691"
                                    ],
                                    "descriptor": {
                                        "name": "Fanisi",
                                        "long_desc": "<p>Fanisi</p>",
                                        "images": [
                                            {
                                                "url": "http://bpp-app.kuza.one/assets/preview/d7/fanisi__preview.png"
                                            }
                                        ]
                                    },
                                    "matched": true,
                                    "quantity": {
                                        "unitized": {
                                            "measure": {
                                                "value": "50",
                                                "unit": "kg"
                                            }
                                        }
                                    }
                                },
                                {
                                    "price": {
                                        "listed_value": "2500.00",
                                        "currency": "KES",
                                        "value": "2500.00"
                                    },
                                    "id": "3186",
                                    "category_ids": [
                                        "694"
                                    ],
                                    "descriptor": {
                                        "name": "Galigan",
                                        "long_desc": "<p>Galigan</p>",
                                        "images": [
                                            {
                                                "url": "http://bpp-app.kuza.one/assets/preview/a1/galigan__05__preview__preview.jpg"
                                            }
                                        ]
                                    },
                                    "matched": true,
                                    "quantity": {
                                        "unitized": {
                                            "measure": {
                                                "value": "5",
                                                "unit": "litre"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            }
        },
        {
            "context": {
                "domain": "retail:1.1.0",
                "action": "on_search",
                "version": "1.1.0",
                "bpp_id": "agrinet-bpp",
                "bpp_uri": "https://agrinet-bpp-network.kuza.one",
                "country": "IND",
                "city": "std:080",
                "location": {
                    "country": {
                        "code": "IND"
                    },
                    "city": {
                        "code": "std:080"
                    }
                },
                "bap_id": "kuza-agrinet-bap.com",
                "bap_uri": "https://bap-network.kuza.one",
                "transaction_id": "cc504a61-8389-4771-a9ff-d5e943c16f20",
                "message_id": "e82a5ab1-3f8d-4789-85c9-e2d34e53305a",
                "ttl": "PT10M",
                "timestamp": "2024-04-12T19:34:51.549Z"
            },
            "error": {
                "code": "30000",
                "message": "[{\"message\":\"No Channel with the token \\\"agrichem-token\\\" could be found\",\"locations\":[{\"line\":2,\"column\":5}],\"path\":[\"facets\"],\"extensions\":{\"code\":\"CHANNEL_NOT_FOUND\"}}]"
            }
        },
        {
            "context": {
                "domain": "retail:1.1.0",
                "action": "on_search",
                "version": "1.1.0",
                "bpp_id": "beckn-sandbox-bpp.becknprotocol.io",
                "bpp_uri": "https://sandbox-bpp-network.becknprotocol.io",
                "country": "IND",
                "city": "std:080",
                "location": {
                    "country": {
                        "code": "IND"
                    },
                    "city": {
                        "code": "std:080"
                    }
                },
                "bap_id": "kuza-agrinet-bap.com",
                "bap_uri": "https://bap-network.kuza.one",
                "transaction_id": "cc504a61-8389-4771-a9ff-d5e943c16f20",
                "message_id": "e82a5ab1-3f8d-4789-85c9-e2d34e53305a",
                "ttl": "PT10M",
                "timestamp": "2024-04-12T19:34:53.569Z"
            },
            "message": {
                "catalog": {
                    "descriptor": {
                        "name": "HBO"
                    },
                    "providers": [
                        {
                            "id": "./retail.kirana/ind.blr/33@tourism-bpp-infra2.becknprotocol.io.provider",
                            "descriptor": {
                                "name": "Venky.Mahadevan@Bazaar"
                            },
                            "locations": [
                                {
                                    "id": "./retail.kirana/ind.blr/1@tourism-bpp-infra2.becknprotocol.io.provider_location",
                                    "gps": "12.909955,77.596316"
                                }
                            ],
                            "categories": [
                                {
                                    "id": "c1",
                                    "descriptor": {
                                        "code": "grocery",
                                        "name": "grocery"
                                    }
                                },
                                {
                                    "id": "c2",
                                    "descriptor": {
                                        "code": "electronics",
                                        "name": "electronics"
                                    }
                                }
                            ],
                            "fulfillments": [
                                {
                                    "id": "f1",
                                    "type": "Delivery",
                                    "tracking": false
                                },
                                {
                                    "id": "f2",
                                    "type": "Self-Pickup",
                                    "tracking": false
                                }
                            ],
                            "items": [
                                {
                                    "id": "./retail.kirana/ind.blr/247@tourism-bpp-infra2.becknprotocol.io.item",
                                    "descriptor": {
                                        "images": [
                                            {
                                                "url": "https://tourism-bpp-infra2.becknprotocol.io/attachments/view/253.jpg"
                                            }
                                        ],
                                        "name": "Isothermal Stainless Steel Hiking Flask MH500 Yellow - Water bottle",
                                        "short_desc": "InstaCuppa Stainless Steel Thermos Flask Water Bottle with Sports Sipper Lid, Double Walled Vacuum Insulation",
                                        "long_desc": "<div> <ul> <li>ULTRA MODERN DESIGN - Our thermos bottle is crafted with a unique and modern design. Gone are the days of old and boring flasks. Guaranteed to impress your colleagues, friends & family.</li> <li>ADVANCED TEMPERATURE CONTROL – A double-wall, vacuum-insulated design helps lock in heat for up to 12 hours and cold for up to 24!</li> <li>ELIMINATES CONDENSATION – Offering improved grip and control, these innovative dual-layer bottles offer a slip-resistant surface that’s free of sweat and condensation..</li> <li>LEAK-PROOF and ECO-FRIENDLY – Remove, and clean, the large, screw on lid provides faster access to water inside and won’t spill a drop even when it’s tipped upside or put in your gym bag.</li> <li>The distress quilted jacket is a versatile fashion choice you can wear on any occasion. A style essential piece for Women which will reveal your strong sense of personality</li> </ul> <div> <p><b>Product Details</b></p> <ul> <li>Advanced Temperature Retention.This thermos water bottle ensures your beverages will remain hot or cold for a long time.Hot for up to 12 hours.Cold for up to 24 hours.</li> <li>Retains Original Flavors.Vacuum insulation ensures this travel thermos water bottle is airtight and retains the original flavor of your beverages.Also, this bottle is B.P.A Free.</li> <li>Premium Quality Materials.This stylish bottle is a double-walled vacuum insulated and made from premium 304-grade stainless steel - which makes this flask bottle.</li> </ul> </div>"
                                    },
                                    "matched": true,
                                    "price": {
                                        "listed_value": "1200.0",
                                        "currency": "INR",
                                        "value": "1200.0"
                                    },
                                    "recommended": true,
                                    "location_id": "./retail.kirana/ind.blr/1@tourism-bpp-infra2.becknprotocol.io.provider_location",
                                    "category_id": "c1",
                                    "fulfillment_id": "f1",
                                    "tags": [
                                        {
                                            "descriptor": {
                                                "name": "item-cataegory"
                                            },
                                            "list": [
                                                {
                                                    "descriptor": {
                                                        "name": "category"
                                                    },
                                                    "value": "retail"
                                                }
                                            ],
                                            "display": true
                                        },
                                        {
                                            "descriptor": {
                                                "name": "item-properties"
                                            },
                                            "list": [
                                                {
                                                    "descriptor": {
                                                        "name": "waterbottle"
                                                    },
                                                    "value": "y"
                                                },
                                                {
                                                    "descriptor": {
                                                        "name": "Trekking"
                                                    },
                                                    "value": "y"
                                                },
                                                {
                                                    "descriptor": {
                                                        "name": "Sipper"
                                                    },
                                                    "value": "y"
                                                },
                                                {
                                                    "descriptor": {
                                                        "name": "Hiking"
                                                    },
                                                    "value": "y"
                                                }
                                            ],
                                            "display": true
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            }
        },
        {
            "context": {
                "domain": "retail:1.1.0",
                "action": "on_search",
                "version": "1.1.0",
                "bpp_id": "agrinet-bpp",
                "bpp_uri": "https://agrinet-bpp-network.kuza.one",
                "country": "IND",
                "city": "std:080",
                "location": {
                    "country": {
                        "code": "IND"
                    },
                    "city": {
                        "code": "std:080"
                    }
                },
                "bap_id": "kuza-agrinet-bap.com",
                "bap_uri": "https://bap-network.kuza.one",
                "transaction_id": "cc504a61-8389-4771-a9ff-d5e943c16f20",
                "message_id": "e82a5ab1-3f8d-4789-85c9-e2d34e53305a",
                "ttl": "PT10M",
                "timestamp": "2024-04-12T19:34:51.549Z"
            },
            "error": {
                "code": "30000",
                "message": "[{\"message\":\"No Channel with the token \\\"agrichem-token\\\" could be found\",\"locations\":[{\"line\":2,\"column\":5}],\"path\":[\"facets\"],\"extensions\":{\"code\":\"CHANNEL_NOT_FOUND\"}}]"
            }
        },
        {
            "context": {
                "domain": "retail:1.1.0",
                "action": "on_search",
                "version": "1.1.0",
                "bpp_id": "agrinet-bpp",
                "bpp_uri": "https://agrinet-bpp-network.kuza.one",
                "country": "IND",
                "city": "std:080",
                "location": {
                    "country": {
                        "code": "IND"
                    },
                    "city": {
                        "code": "std:080"
                    }
                },
                "bap_id": "kuza-agrinet-bap.com",
                "bap_uri": "https://bap-network.kuza.one",
                "transaction_id": "cc504a61-8389-4771-a9ff-d5e943c16f20",
                "message_id": "e82a5ab1-3f8d-4789-85c9-e2d34e53305a",
                "ttl": "PT10M",
                "timestamp": "2024-04-12T19:34:51.549Z"
            },
            "error": {
                "code": "30000",
                "message": "[{\"message\":\"No Channel with the token \\\"agrichem-token\\\" could be found\",\"locations\":[{\"line\":2,\"column\":5}],\"path\":[\"facets\"],\"extensions\":{\"code\":\"CHANNEL_NOT_FOUND\"}}]"
            }
        }
    ]
}
